# Generated by Django 4.0.5 on 2022-07-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miblog', '0002_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
